### ISSUE TITLE
Skipping beyond just the intro

### ISSUE THREAD

**Issue by gigiwest123** [Hellowlol/bw_plex#126]
2020-04-10 10:51:15,076 :: bw_plex :: DEBUG :: plex.py:1191 :: Found One-Punch.Man.s02e06 theme start 00:25, theme end 06:35, ffmpeg_end 00:00 progress 12:20 fake_progress 12:30 best_time 06:35 credits_start 00:00 credits_end 00:00,

Happens randomly with different shows. This was the longest skip so far, its a little annoying and defeats the purpose of having this installed :( 

Any ideas?

**Comment by Hellowlol** [comment]
Nope, i need the entire log. 

This program has serval issues but in this case there we fail to detect the correct end of the intro

This can be of different reasons but most of the times it because the show uses the theme song different places in the first 15 minutes and we try pick correct theme sequence and fail. 

The best corse is action would be to manually set the correct time (it’s cli option)
