### ISSUE TITLE
Download theme from plex

### ISSUE THREAD

**Issue by nick-traeger** [Hellowlol/bw_plex#18]
Is it an option to get the theme from `http://tvthemes.plexapp.com/<tvdb-id>.mp3` instead of youtube? Maybe i can try to implement this.

**Comment by Hellowlol** [comment]
I have already tried that, infact that was my first solution. The themes was simply not good enoght to match correctly. They was to short (so the audiofingerprint didnt get the entire song) or they didnt match at all because they where changed (i assumed it was for copyright reasons.)

You can find the code here: https://github.com/Hellowlol/bw_plex/blob/master/bw_plex/misc.py#L60-L94

**Comment by Hellowlol** [comment]
You could make this this configurable. I have started on this on https://github.com/Hellowlol/bw_plex/blob/master/bw_plex/plex.py#L463-L500

**Comment by Hellowlol** [comment]
Closing this as this can now be set in the config file
